theme: minima
title: github
author: kruthi
email: kruthi@gmail.com
description: thhe is something that i didn't like at all....whhhat the hell is this _posts directory i didn't get it and i am struggling a lot to complete it....

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
